name = "TBA-Lite"
author = "Slash"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91ffbc32ec7ffbdd9a2d40dbae9ca1b2fcb64850d837758b8a51d9fb9728d377"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
