name = "TBA-Lite"
author = "Slash"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdd41657060fa8fa5bb656fd43b8fb1d37f481d7b76bb6d8557451e3103bef2d"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
